internal/common/database/helper.go
internal/vendors/accessor.go
internal/vendors/accessor_spec.go
internal/vendors/accessor_test.go
internal/vendors/service.go
internal/vendors/service_mock.go
internal/vendors/service_spec.go
internal/vendors/service_test.go
router/helper.go
router/vendor.go

- Create test for paginated view all vendor accessor
- Create test for paginated view all vendor service
- Create implementation for paginated view all vendor accessor
- Create implementation for paginated view all vendor service
- ADU-16: https://linear.app/adudu/issue/ADU-16/get-list-of-vendors-api
- ADU-23: https://linear.app/adudu/issue/ADU-23/ut-for-get-list-of-vendors-api

PBI 16&23: Get List of Vendors Paginated

---

.github/workflows/sonarcloud.yml
internal/inventory/accessor.go
internal/inventory/accessor_test.go
internal/inventory/inventory.go

- Create test for Update information on existing inventory items accessor
- Add Update information on existing inventory items accessor implementation
- ADU-35: [Update information on existing inventory items API](https://linear.app/adudu/issue/ADU-35/update-information-on-existing-inventory-items-api)
- ADU-42: [UT for update information on existing inventory items API](https://linear.app/adudu/issue/ADU-42/ut-for-update-information-on-existing-inventory-items-api)

PBI 35&42 : Update Information on Existing Inventory Items

---

.github/workflows/sonarcloud.yml
internal/inventory/accessor.go
internal/inventory/accessor_test.go
internal/inventory/inventory.go

- Create test for Update information on existing inventory items accessor
- Add Update information on existing inventory items accessor implementation
- ADU-35: [Update information on existing inventory items API](https://linear.app/adudu/issue/ADU-35/update-information-on-existing-inventory-items-api)
- ADU-42: [UT for update information on existing inventory items API](https://linear.app/adudu/issue/ADU-42/ut-for-update-information-on-existing-inventory-items-api)

Pbi 35 42 updateinformation on existing inventory items

---

internal/product/accessor.go
internal/product/accessor_test.go
internal/product/product.go
internal/product/service.go
internal/product/service_mock.go
internal/product/service_test.go
router/product.go

- Implement get vendor product by name accessor
- Implement get vendor product by name service
- Implement order by for get vendor product accessor
- Implement order by for get vendor product service
- Query parameter wiring for both filter and order by
- UT for filter vendor product by name
- ADU-32: https://linear.app/adudu/issue/ADU-32/filter-vendor-product-by-name-api
- ADU-41: https://linear.app/adudu/issue/ADU-41/ut-for-filter-vendor-product-by-name-api

PBI 32-41: Filter Vendor Product by Name

---

.air.toml
.gitignore
README.md

- Add toml config for Air (Air is a Hot-reload framework)
- Add gitignore for tmp files from Air build
- ADU-72: https://linear.app/adudu/issue/ADU-72/setup-air-hot-reload-framework

PBI-72: Setup Air config

---

cmd/config/config.go
router/vendor.go

- Add routing path to be Get Vendor By ID
- ADU-51: https://linear.app/adudu/issue/ADU-51/get-vendor-by-id-api
- ADU-52: https://linear.app/adudu/issue/ADU-52/ut-for-get-vendor-by-id

PBI-51-52: Get Vendor By ID

---

cmd/config/config.go
config.example.jsonc
internal/product/accessor.go
internal/product/accessor_test.go
internal/vendors/accessor.go
internal/vendors/accessor_test.go
router/product.go
router/vendor.go

- Adjust typo on router config which caused app to not running properly
- Change function to receive path param on vendor router
- Remove small typo on update db query 
- ADU-74: https://linear.app/adudu/issue/ADU-74/fix-router-bugs

PBI-74: FixRouterBugs

---

go.mod
go.sum
internal/common/database/postgres.go
internal/common/database/postgres_mock.go
internal/product/accessor.go
internal/product/accessor_test.go
internal/product/product.go
internal/vendors/accessor.go
internal/vendors/accessor_test.go
internal/vendors/service_test.go
internal/vendors/vendor.go

- Integrate `sqlx` framework to ease accessor implementations

Pbi chore: sqlx integration

---

internal/account/account.go
migrations/20241009070631_create_account_table.sql

- Create Account Schema
- Create Account table migration
- ADU-128: https://linear.app/adudu/issue/ADU-128/account-db-schema

PBI 128: Create Account Schema and Migration

---

internal/account/account.go
migrations/20241009070631_create_account_table.sql

- Add modified date field to the Account Schema
- Fix id type in Account type
- ADU-128: https://linear.app/adudu/issue/ADU-128/account-db-schema

PBI 128: Fix Account Schema

---

.air.toml
internal/common/database/postgres.go
internal/product/accessor.go
internal/product/service.go

- Hotfix `Queryx` interface not unpacking

PBI chore: hotfix query args not unpacked

---

cmd/config/config.go
config.example.jsonc
internal/vendors/accessor.go
internal/vendors/accessor_test.go
internal/vendors/service.go
internal/vendors/service_mock.go
internal/vendors/service_test.go
router/vendor.go

- Implement get all locations accessor
- Implement get locations service
- Implement get locations routing: `GET /vendor/location`
- Create UT for the accessor and service
- Response Example:
- ADU-132: https://linear.app/adudu/issue/ADU-132/get-all-vendor-locations-api

PBI 132: Get All Vendor Locations

---

cmd/config/config.go
config.example.jsonc
internal/account/idgenerator_test.go
internal/common/database/helper.go
internal/vendors/accessor_spec.go
router/product.go
router/vendor.go

- Fix misplaced config
- Standardize API response to valid json

Pbi chores standardize response

---

cmd/config/config.go
cmd/main.go
config.example.jsonc
internal/account/accessor.go
internal/account/accessor_test.go
internal/account/account.go
internal/account/service.go
internal/account/service_mock.go
internal/account/service_test.go
router/account.go

- UT for authentication
- Implement authentication account accessor
- Implement authentication account service
- Implement authentication account routing
- ADU-124: https://linear.app/adudu/issue/ADU-124/authentication-accessor
- ADU-125: https://linear.app/adudu/issue/ADU-125/authentication-service
- ADU-126: https://linear.app/adudu/issue/ADU-126/[unit-test]-authentication-service
- ADU-127: https://linear.app/adudu/issue/ADU-127/[unit-test]-authentication-accessor

PBI-124-125-126-127: Authentication

---

internal/common/middleware/auth.go
internal/common/middleware/auth_test.go
internal/token/service.go
internal/token/service_test.go

Add middleware for authentication authorization using JWT. Currently it is not implemented. We should create another branch to implement it to prevent merge conflicts
PBI-98 : https://linear.app/adudu/issue/ADU-98/jwt-handler-middleware
PBI-118: https://linear.app/adudu/issue/ADU-118/unit-test-for-jwt-middleware

 PBI-98-118-Middleware JWT

---

router/product.go
router/vendor.go

PBI-chore: router return on error

---

router/helper.go

- Add limit query param to pagination spec

PBI chore: add pagination limit

---

Makefile
fixtures/product/product_vendor.jsonc
fixtures/product/uom.jsonc
fixtures/vendors/vendor.jsonc
internal/product/accessor.go
internal/product/accessor_test.go
internal/product/product.go
internal/product/seeder_test.go
migrations/20241002085412_create_product_vendor_table.sql
migrations/20241031141552_create_product_vendor_v2.sql
scripts/seeder/main.go

- Revamp product vendor table to the client's requirement
- Adjust seeders and fixtures

Pbi chore: Product Vendor table v2

---

internal/account/accessor.go

Update Find Account by Email Query
ADU-124: https://linear.app/adudu/issue/ADU-124/authentication-accessor
ADU-125: https://linear.app/adudu/issue/ADU-125/authentication-service
ADU-126: [https://linear.app/adudu/issue/ADU-126/[unit-test]-authentication-service](https://linear.app/adudu/issue/ADU-126/%5Bunit-test%5D-authentication-service)
ADU-127: [https://linear.app/adudu/issue/ADU-127/[unit-test]-authentication-accessor](https://linear.app/adudu/issue/ADU-127/%5Bunit-test%5D-authentication-accessor)

PBI-124-125-126-127 : Fix Query Authentication Backend

---

internal/product/accessor.go
internal/product/accessor_test.go
internal/product/contract.go
internal/product/service.go
internal/product/service_mock.go
internal/product/service_test.go

- Made a new accessor to fetch price data from ID
- Populate price data into product vendor
- https://linear.app/adudu/issue/ADU-158/populate-any-payload-with-product-vendor-with-their-respective-prices

Pbi 158: Populate price into product vendor

---

internal/product/accessor.go
internal/product/accessor_test.go
internal/product/contract.go
internal/product/service.go
internal/product/service_mock.go
internal/product/service_test.go

- Adjust UT for accessor, service
- Create desired payload schema
- Adjust accessor
- Adjust service
- ADU-191: https://linear.app/adudu/issue/ADU-191/sync-getproductvendor-response

PBI 191: Sync Get Product Vendors Response

---

cmd/config/config.go
cmd/main.go
config.example.jsonc
internal/mailer/accessor.go
internal/mailer/accessor_spec.go
internal/mailer/accessor_test.go
internal/mailer/mailer.go
internal/mailer/service.go
internal/mailer/service_mock.go
internal/mailer/service_test.go
router/email-status.go

This PR exposes API endpoint to get email status, paginated
PBI-152:[ API to get all email status](https://linear.app/adudu/issue/ADU-152/api-to-get-all-email-status)

PBI-152: API Email Status

---

internal/vendors/accessor.go
internal/vendors/accessor_test.go

- Adjust fix in accessor UT
- Adjust implementation in accessor
- ADU-193: https://linear.app/adudu/issue/ADU-193/[chore]-fix-get-vendor-by-product-name-be

CHORE-193: Fix Get Vendor by Product Name

---

internal/product/accessor.go
internal/product/accessor_test.go
internal/product/contract.go
internal/product/service.go
internal/product/service_mock.go
internal/product/service_test.go

- Implemented getUOMByID functionality
- Updated the price payload to include UOM information.
- Added the quantity field to the price response
https://linear.app/adudu/issue/ADU-197/enrich-price-payload-with-the-respective-uom

Pbi 198: Populate price payload with uom

---

cmd/config/config.go
config.example.jsonc
internal/account/accessor.go
internal/account/accessor_test.go
internal/account/service.go
internal/account/service_mock.go
internal/account/service_test.go
router/account.go

- Implemented `FindAccountByID` method.
- Added `GetCurrentUser` endpoint to fetch user from JWT token.
- https://linear.app/adudu/issue/ADU-190/get-current-user-from-jwt-token

PBI 190: Get Current User

---

internal/mailer/accessor.go
internal/mailer/accessor_test.go

With this PR, now user can filter by email
PBI-198: https://linear.app/adudu/issue/ADU-199/backend-filter-emailed-vendors

PBI-198: Filter Email Vendor

---

cmd/config/config.go
config.example.jsonc
internal/mailer/accessor_spec.go
internal/mailer/accessor_test.go
internal/vendors/accessor.go
internal/vendors/accessor_test.go
internal/vendors/service.go
internal/vendors/service_mock.go
internal/vendors/service_test.go
internal/vendors/vendor.go
migrations/20241128042455_create_vendor_evaluation_table.sql
router/vendor.go

- Add new table storing evaluations for a vendor
- Create an API to create an evaluation
- Implemented service and accessor to create vendor evaluation
- Screenshot:
- PBI-205: https://linear.app/adudu/issue/ADU-205/backend-form-evaluasi

PBI-205: Create vendor evaluation
